name: Update pages

on:
  schedule:
    - cron: '5 * * * *'
  workflow_dispatch:

concurrency: update

jobs:

  update:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    env:
      CACTUS_CONFIG: ${{ secrets.CACTUS_CONFIG }}

    steps:
      - uses: arch4edu/cactus/actions/upgrade-archlinux@main

      - name: Install runtime dependencies
        run: pacman -S --noconfirm --needed git python-django python-mysqlclient python-pygithub python-requests python-tornado python-yaml

      - uses: actions/checkout@master
        with:
          path: pages

      - uses: actions/checkout@master
        with:
          repository: arch4edu/cactus
          path: cactus

      - uses: actions/checkout@master
        with:
          repository: petronny/djangorm
          path: djangorm

      - uses: actions/checkout@master
        with:
          repository: arch4edu/mirrorlist
          path: mirrorlist

      - uses: petronny/git-config-user@master
        with:
          path: pages

      - name: Update pages
        run: |
          cp pages/update-build-status.py cactus
          python -m cactus.update-build-status

          cd pages
          python3 update-mirror-status.py ../mirrorlist

          git add index.md mirrors.md
          git commit -m "[$(date)] auto update" || exit 0
          git push
