name: Update pages

on:
  schedule:
    - cron: '5 * * * *'
  workflow_dispatch:

concurrency: update

jobs:

  publish:
    runs-on: ubuntu-latest
    container:
      image: archlinux
    env:
      CACTUS_CONFIG: ${{ secrets.CACTUS_CONFIG }}

    steps:
      - name: Get time
        id: time
        run: echo "::set-output name=time::$(date +%F-%T)"

      - name: Set up pacman package cache
        uses: actions/cache@master
        with:
          path: /var/cache/pacman/pkg
          key: pacman-package-x86_64-${{ steps.time.outputs.time }}
          restore-keys: pacman-package-x86_64-

      - name: Install runtime dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm --needed git python-django python-mysqlclient python-pygithub python-tornado python-yaml

      - uses: actions/checkout@master
        with:
          path: pages

      - uses: actions/checkout@master
        with:
          repository: arch4edu/cactus
          path: cactus

      - uses: actions/checkout@master
        with:
          repository: petronny/djangorm
          path: djangorm

      - uses: petronny/git-config-user@master
        with:
          path: pages

      - name: Update pages
        run: |
          cp pages/update-pages.py cactus
          python -m cactus.update-pages

          cd pages
          git add index.md
          git commit -m "[$(date)] auto update" || exit 0
          git push
